version: "3"

includes:
  c:
    taskfile: ../common
    dir: ../common

tasks:
  default:
    desc: Install minimal set of used languages
    cmds:
      - task: bash
      - task: pwsh
      - task: zsh
  bash:
    cmds:
      - cmd: echo "bash is already installed"
        platforms: [darwin, linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:git;scoop:git;winget:Git.Git"]
        platforms: [windows]
    desc: Install Bash

  # bash:ohmybash: # https://github.com/ohmybash/oh-my-bash

  fish: # https://fishshell.com/
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["cask/gitkraken"]
        platforms: [darwin]
      - task: c:linux
        vars:
          PACKAGES: ["apt:fish;apk:fish;dnf:fish;brew:fish"]
        platforms: [linux]
      - cmd: echo "fish shell is only available under wsl or cygwin"
        platforms: [windows]
    desc: Install Fish Shell

  # fish:ohmyfish: # https://github.com/oh-my-fish/oh-my-fish

  nushell: # https://www.nushell.sh/
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["nushell"]
        platforms: [darwin]
      - cmd: |
          if command -v apk; then
            echo "https://alpine.fury.io/nushell/" | tee -a /etc/apk/repositories
            apk update
            apk add --allow-untrusted nushell
          elif command -v apt; then
            curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
            echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
            sudo apt update
            sudo apt install nushell
          elif command -v dnf; then
            echo "[gemfury-nushell]
            name=Gemfury Nushell Repo
            baseurl=https://yum.fury.io/nushell/
            enabled=1
            gpgcheck=0
            gpgkey=https://yum.fury.io/nushell/gpg.key" | sudo tee /etc/yum.repos.d/fury-nushell.repo
            sudo dnf install -y nushell
          else
            brew install nushell
          fi
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:nushell;scoop:nu;winget:nushell"]
        platforms: [windows]
    desc: Install Nushell

  # nushell:awesome-nu: # https://github.com/nushell/awesome-nu

  pwsh:
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["cask/powershell"]
        platforms: [darwin]
      - cmd: bash ./pwsh-install.sh
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:pwsh;scoop:main/pwsh;winget:Microsoft.PowerShell"]
        platforms: [windows]
    desc: Install Powershell

  ohmyposh:
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["oh-my-posh"]
        platforms: [darwin]
      - cmd: |
          mkdir -p ~/bin
          curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/bin
          # brew install jandedobbeleer/oh-my-posh/oh-my-posh
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:oh-my-posh;winget:JanDeDobbeleer.OhMyPosh"]
        platforms: [windows]
      - cmd: |
          echo "Configure"i
        platforms: [darwin, linux]
      - cmd: |
          echo "Configure"
        platforms: [windows]
    desc: Install OhMyPosh

  # starship: # https://starship.rs/

  utils:
    cmds:
      - task: c:darwin
        vars:
          PACKAGES:
            - autojump # https://github.com/wting/autojump
            - fzf # https://junegunn.github.io/fzf/
            - tmux
        platforms: [darwin]
      # https://yazi-rs.github.io/
      # TODO: Maybe create a separate task for yazi
      - cmd: brew install yazi ffmpeg sevenzip jq poppler fd ripgrep fzf zoxide resvg imagemagick font-symbols-only-nerd-font
        platforms: [darwin]
      - task: c:linux
        vars:
          PACKAGES:
            - ???
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            - autojump
        platforms: [windows]

  zsh:
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: [zsh]
        platforms: [darwin]
      - task: c:linux
        vars:
          PACKAGES: []
        platforms: [linux]
      - cmd: echo "ZSH can only be used in WSL"
        platforms: [windows]
    desc: Install Zsh

  # zsh:ohmyzsh: # https://ohmyz.sh/
