version: "3"

includes:
  c:
    taskfile: ../common
    dir: ../common
  u:
    taskfile: ../utils
    dir: ../utils

tasks:
  default:
    desc: Install minimal set of used languages
    cmds:
      - task: bash
      - task: pwsh
      - task: zsh
  bash:
    cmds:
      - cmd: echo "bash is already installed"
        platforms: [darwin, linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:Git.Git;choco:git;scoop:git"]
        platforms: [windows]
    desc: Install Bash

  # bash:ohmybash: # https://github.com/ohmybash/oh-my-bash

  fish: # https://fishshell.com/
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["cask/gitkraken"]
        platforms: [darwin]
      - task: c:linux
        vars:
          PACKAGES: ["apt:fish;apk:fish;dnf:fish;brew:fish"]
        platforms: [linux]
      - cmd: echo "fish shell is only available under wsl or cygwin"
        platforms: [windows]
    desc: Install Fish Shell

  # fish:ohmyfish: # https://github.com/oh-my-fish/oh-my-fish

  nushell: # https://www.nushell.sh/
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["nushell"]
        platforms: [darwin]
      - cmd: |
          if command -v apk; then
            echo "https://alpine.fury.io/nushell/" | tee -a /etc/apk/repositories
            apk update
            apk add --allow-untrusted nushell
          elif command -v apt; then
            curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
            echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
            sudo apt update
            sudo apt install nushell
          elif command -v dnf; then
            echo "[gemfury-nushell]
            name=Gemfury Nushell Repo
            baseurl=https://yum.fury.io/nushell/
            enabled=1
            gpgcheck=0
            gpgkey=https://yum.fury.io/nushell/gpg.key" | sudo tee /etc/yum.repos.d/fury-nushell.repo
            sudo dnf install -y nushell
          else
            brew install nushell
          fi
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:nushell;choco:nushell;scoop:nu"]
        platforms: [windows]
    desc: Install Nushell

  # nushell:awesome-nu: # https://github.com/nushell/awesome-nu

  pwsh:
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["cask/powershell"]
        platforms: [darwin]
      - cmd: bash ./pwsh-install.sh
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:Microsoft.PowerShell;choco:pwsh;scoop:main/pwsh"]
        platforms: [windows]
    desc: Install Powershell

  ohmyposh:
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["oh-my-posh"]
        platforms: [darwin]
      - cmd: |
          mkdir -p ~/.local/bin
          curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
          # brew install jandedobbeleer/oh-my-posh/oh-my-posh
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:JanDeDobbeleer.OhMyPosh;choco:oh-my-posh"]
        platforms: [windows]
      - cmd: |
          echo "Configure"
        platforms: [darwin, linux]
      - cmd: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./ohmyposh-config.ps1
        platforms: [windows]
    desc: Install OhMyPosh
    deps:
      - task: u:zip

  # starship: # https://starship.rs/

  zsh:
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: [zsh]
        platforms: [darwin]
      - task: c:linux
        vars:
          PACKAGES: [apk:zsh;apt:zsh]
        platforms: [linux]
      - cmd: echo "ZSH can only be used in WSL"
        platforms: [windows]
    desc: Install Zsh

  # zsh:ohmyzsh: # https://ohmyz.sh/
