version: "3"

includes:
  c:
    taskfile: ../common
    dir: ../common
  l:
    taskfile: ../language
    dir: ../language

tasks:
  default:
    desc: Install minimal set of used languages
    cmds:
      - task: jj
      - task: git
      - task: gitkraken
      - task: gh
  git:
    desc: Install Git
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["git"]
        platforms: [darwin]
      - cmd: sudo apt install -y git
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:Git.Git;choco:git;scoop:git"]
        platforms: [windows]
      - task: git:config

  git:config:
    desc: Backup and link Git configuration files
    cmds:
      - cmd: |
          # Handle .gitconfig file
          if [ -f "$HOME/.gitconfig" ]; then
            echo "Backing up existing .gitconfig to $HOME/.gitconfig.bak.$(date +%s)"
            mv "$HOME/.gitconfig" "$HOME/.gitconfig.bak.$(date +%s)"
          fi
          echo "Linking .gitconfig to $HOME/.gitconfig"
          ln -sf "$(pwd)/git.config/gitconfig" "$HOME/.gitconfig"

          # Handle .gitattributes file
          if [ -f "$HOME/.gitattributes" ]; then
            echo "Backing up existing .gitattributes to $HOME/.gitattributes.bak.$(date +%s)"
            mv "$HOME/.gitattributes" "$HOME/.gitattributes.bak.$(date +%s)"
          fi
          echo "Linking .gitattributes to $HOME/.gitattributes"
          ln -sf "$(pwd)/git.config/gitattributes" "$HOME/.gitattributes"
        platforms: [darwin, linux]
      - cmd: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./git-config.ps1
        platforms: [windows]

  gitkraken:
    desc: Install GitKraken
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["cask/gitkraken"]
        platforms: [darwin]
      - cmd: sudo snap install gitkraken --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            ["winget:Axosoft.GitKraken;choco:gitkraken;scoop:extras/gitkraken"]
        platforms: [windows]

  gh:
    desc: Install GitHub CLI
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["gh"]
        platforms: [darwin]
      - cmd: sudo apt install -y gh
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:GitHub.cli;choco:gh;scoop:gh"]
        platforms: [windows]

  # https://jj-vcs.github.io/jj/latest/install-and-setup/
  #
  jj:
    desc: Install JJ Version Control
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["jj"]
        platforms: [darwin]
      - task: c:windows
        cmd: |
          # To install the latest release
          cargo install --locked --bin jj jj-cli
        platforms: [linux, windows]
    deps:
      - task: l:cpp
      - task: l:rust

  lazygit:
    desc: Install LazyGit
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["lazygit"]
        platforms: [darwin]
      - cmd: sudo snap install lazygit --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            ["winget:JesseDuffield.lazygit;choco:lazygit;scoop:extras/lazygit"]
        platforms: [windows]
