version: "3"

includes:
  c:
    taskfile: ../common
    dir: ../common

tasks:
  default:
    desc: default action - lists the tasks (you're looking at it)
    silent: true
    cmds:
      - task --list
  minimal:
    desc: Install minimal set of used languages
    cmds:
      - task: git
      - task: gitconfig
      - task: gitkraken
      - task: gh
  git:
    desc: Install Git
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["git"]
        platforms: [darwin]
      - cmd: sudo apt install -y git
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:git;scoop:git;winget:Git.Git"]
        platforms: [windows]
      - task: git:config
  git:config:
    desc: Backup and link Git configuration files
    cmds:
      - cmd: |
          # Handle .gitconfig file
          if [ -f "$HOME/.gitconfig" ]; then
            echo "Backing up existing .gitconfig to $HOME/.gitconfig.bak.$(date +%s)"
            mv "$HOME/.gitconfig" "$HOME/.gitconfig.bak.$(date +%s)"
          fi
          echo "Linking .gitconfig to $HOME/.gitconfig"
          ln -sf "$(pwd)/.git-config/.gitconfig" "$HOME/.gitconfig"

          # Handle .gitattributes file
          if [ -f "$HOME/.gitattributes" ]; then
            echo "Backing up existing .gitattributes to $HOME/.gitattributes.bak.$(date +%s)"
            mv "$HOME/.gitattributes" "$HOME/.gitattributes.bak.$(date +%s)"
          fi
          echo "Linking .gitattributes to $HOME/.gitattributes"
          ln -sf "$(pwd)/.git-config/.gitattributes" "$HOME/.gitattributes"
        platforms: [darwin, linux]
      - cmd: |
          pwsh.exe -File ./gitconfig.ps1
        platforms: [windows]
  gitkraken:
    desc: Install GitKraken
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["cask/gitkraken"]
        platforms: [darwin]
      - cmd: sudo snap install gitkraken --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:gitkraken;scoop:extras/gitkraken;winget:Axosoft.GitKraken"]
        platforms: [windows]
  gh:
    desc: Install GitHub CLI
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["gh"]
        platforms: [darwin]
      - cmd: sudo apt install -y gh
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:gh;scoop:gh;winget:GitHub.cli"]
        platforms: [windows]
  lazygit:
    desc: Install LazyGit
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["lazygit"]
        platforms: [darwin]
      - cmd: sudo snap install lazygit --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:lazygit;scoop:extras/lazygit;winget:JesseDuffield.lazygit"]
        platforms: [windows]
