version: "3"

includes:
  c:
    taskfile: ../common
    dir: ../common
  l:
    taskfile: ../language
    dir: ../language
  u:
    taskfile: ../utils
    dir: ../utils

tasks:
  default:
    desc: Install minimal list of IDEs based on the operating system
    cmds:
      - task: clion
      - task: goland
      - task: neovim
      - task: vscode
      - task: vscodium
      - task: zed
      - task: pycharm
      - task: sublime

  clion:
    desc: Install CLion IDE
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["clion"]
        platforms: [darwin]
      - cmd: sudo snap install clion --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            ["winget:JetBrains.CLion;choco:clion-ide;scoop:extras/clion"]
        platforms: [windows]

  coursor:
    desc: Install Coursor
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["coursor"]
        platforms: [darwin]
      - cmd: sudo snap install coursor
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            ["winget:Coursor.Coursor;choco:coursor;scoop:extras/coursor"]
        platforms: [windows]

  goland:
    desc: Install GoLand IDE
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["goland"]
        platforms: [darwin]
      - cmd: sudo snap install goland --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:JetBrains.GoLand;choco:goland;scoop:extras/goland"]
        platforms: [windows]

  neovim:
    aliases: [nvim]
    desc: Install Neovim
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["neovim", "neovim-qt"]
        platforms: [darwin]
      - cmd: sudo snap install nvim --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            - "winget:Neovim.Neovim;choco:neovim;scoop:main/neovim"
        platforms: [windows]
      - cmd: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./neovim-config/Build-LuaTiktoken.ps1
        platforms: [windows]
      - task: neovim:config
    deps:
      - task: l:llvm
      - task: l:lua
      - task: l:node
      - task: l:rust
      - task: u:fzf
      - task: u:zip
    summary: |
      Inspired from
       - https://www.lazyvim.org
       - https://www.youtube.com/watch?v=evCmP4hH7ZU

  neovim:config:
    desc: Install Neovim config
    cmds:
      - cmd: |
          bash ./neovim-config.sh
        platforms: [darwin, linux]
      - cmd: |
          pwsh.exe -File ./neovim-config.ps1
        platforms: [windows]

  neovim:fix-git:
    desc: Fix Git "dubious ownership" errors for Neovim plugins
    cmds:
      - cmd: |
          pwsh.exe -File ./fix-neovim-git.ps1
        platforms: [windows]
      - cmd: |
          pwsh.exe -Command "& { . './neovim-config.ps1'; Add-NeovimPluginsToGitSafeDirectory -ConfigPath (Join-Path -Path $PWD -ChildPath 'neovim-config') }"
        platforms: [windows]

  vscode:
    desc: Install VS Code
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["visual-studio-code"]
        platforms: [darwin]
      - cmd: sudo snap install code --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            [
              "winget:Microsoft.VisualStudioCode;choco:vscode;scoop:extras/vscode",
            ]
        platforms: [windows]

  vscode:insiders:
    desc: Install VS Code Insiders
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["visual-studio-code-insiders"]
        platforms: [darwin]
      - cmd: sudo snap install code-insiders --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            [
              "winget:Microsoft.VisualStudioCode.Insiders;choco:vscode-insiders;scoop:extras/vscode-insiders",
            ]
        platforms: [windows]

  vscodium:
    desc: Install VSCodium (open source build of VS Code)
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["vscodium"]
        platforms: [darwin]
      - cmd: sudo snap install codium --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            ["winget:VSCodium.VSCodium;choco:vscodium;scoop:extras/vscodium"]
        platforms: [windows]

  vscodium:insiders:
    desc: Install VSCodium Insiders (open source build of VS Code Insiders)
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["vscodium-insiders"]
        platforms: [darwin]
      - cmd: sudo snap install codium-insiders --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            [
              "winget:VSCodium.VSCodium.Insiders;choco:vscodium-insiders;scoop:extras/vscodium-insiders",
            ]
        platforms: [windows]

  zed:
    desc: Install Zed
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["zed"]
        platforms: [darwin]
      - cmd: curl -f https://zed.dev/install.sh | sh
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:Zed.Zed;scoop:extras/zed"]
        platforms: [windows]

  pycharm:
    desc: Install PyCharm
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["pycharm"]
        platforms: [darwin]
      - cmd: sudo snap install pycharm-professional --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            [
              "winget:JetBrains.PyCharm.Professional;choco:pycharm-professional;scoop:extras/pycharm-professional",
            ]
        platforms: [windows]

  sublime:
    desc: Install Sublime Text
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["sublime-text"]
        platforms: [darwin]
      - cmd: sudo snap install sublime-text --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            [
              "winget:SublimeHQ.SublimeText.4;choco:sublimetext4;scoop:extras/sublime-text",
            ]
        platforms: [windows]

  trae:
    desc: Install Trae
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["trae"]
        platforms: [darwin]
      - cmd: sudo snap install trae --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["winget:Trae.Trae;choco:trae;scoop:extras/trae"]
        platforms: [windows]
