version: '3'

includes:
  common: ./common/Taskfile.yml

vars:
  SHELL:
    sh: bash
    windows: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command

tasks:
  default:
    desc: default action - lists the tasks (you're looking at it)
    silent: true
    cmds:
      - task --list

  minimal:
    desc: Install minimal list of IDEs based on the operating system
    cmds:
      - task: clion
      - task: goland
      - task: neovim
      - task: vscode
      - task: vscodium
      - task: zed
      - task: pycharm
      - task: sublime

  clion:
    desc: Install CLion IDE
    cmds:
      - cmd: brew install clion
        platforms: [darwin]
      - cmd: sudo snap install clion --classic
        platforms: [linux]
      - cmd: |
          choco install clion-ide -y || scoop bucket add extras && scoop install extras/clion || winget install -e --id JetBrains.CLion
        platforms: [windows]

  goland:
    desc: Install GoLand IDE
    cmds:
      - cmd: brew install goland
        platforms: [darwin]
      - cmd: sudo snap install goland --classic
        platforms: [linux]
      - cmd: |
          choco install goland -y || scoop bucket add extras && scoop install extras/goland || winget install -e --id JetBrains.GoLand
        platforms: [windows]

  neovim:
    desc: Install Neovim
    cmds:
      - cmd: brew install neovim neovim-qt
        platforms: [darwin]
      - cmd: sudo snap install nvim --classic
        platforms: [linux]
      - cmd: |
          choco install lua luarocks neovim -y || scoop bucket add main && scoop install main/lua main/luarocks main/neovim || winget install --id Neovim.Neovim -e
        platforms: [windows]
      - task: neovim-config

  neovim-config:
    desc: Install Neovim config
    cmds:
      - cmd: |
          echo "TODO: Integrate the neovim config in the same repo as the Taskfile"

  vscode:
    desc: Install VS Code
    cmds:
      - cmd: brew install visual-studio-code
        platforms: [darwin]
      - cmd: sudo snap install code --classic
        platforms: [linux]
      - cmd: |
          choco install vscode -y || scoop bucket add extras && scoop install extras/vscode || winget install -e --id Microsoft.VisualStudioCode
        platforms: [windows]

  vscodium:
    desc: Install VSCodium (open source build of VS Code)
    cmds:
      - cmd: brew install vscodium
        platforms: [darwin]
      - cmd: sudo snap install codium --classic
        platforms: [linux]
      - cmd: |
          choco install vscodium -y || scoop bucket add extras && scoop install extras/vscodium || winget install -e --id VSCodium.VSCodium
        platforms: [windows]

  zed:
    desc: Install Zed
    cmds:
      - cmd: brew install zed
        platforms: [darwin]
      - cmd: curl -f https://zed.dev/install.sh | sh
        platforms: [linux]
      # Unofficial Windows install
      - cmd: scoop bucket add extras && scoop install extras/zed
        platforms: [windows]

  pycharm:
    desc: Install PyCharm
    cmds:
      - cmd: brew install pycharm
        platforms: [darwin]
      - cmd: sudo snap install pycharm-professional --classic
        platforms: [linux]
      - cmd: |
          choco install pycharm-professional -y || scoop bucket add extras && scoop install extras/pycharm-professional || winget install -e --id JetBrains.PyCharm.Professional
        platforms: [windows]

  sublime:
    desc: Install Sublime Text
    cmds:
      - cmd: brew install sublime-text
        platforms: [darwin]
      - cmd: sudo snap install sublime-text --classic
        platforms: [linux]
      - cmd: |
          choco install sublimetext4 -y || scoop bucket add extras && scoop install extras/sublime-text || winget install -e --id SublimeHQ.SublimeText.4
        platforms: [windows]

