version: "3"

includes:
  c:
    taskfile: ../common
    dir: ../common

tasks:
  default:
    desc: Install minimal list of IDEs based on the operating system
    cmds:
      - task: clion
      - task: goland
      - task: neovim
      - task: vscode
      - task: vscodium
      - task: zed
      - task: pycharm
      - task: sublime

  clion:
    desc: Install CLion IDE
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["clion"]
        platforms: [darwin]
      - cmd: sudo snap install clion --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:clion-ide;scoop:extras/clion;winget:JetBrains.CLion"]
        platforms: [windows]

  goland:
    desc: Install GoLand IDE
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["goland"]
        platforms: [darwin]
      - cmd: sudo snap install goland --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:goland;scoop:extras/goland;winget:JetBrains.GoLand"]
        platforms: [windows]

  neovim:
    desc: Install Neovim
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["neovim", "neovim-qt"]
        platforms: [darwin]
      - cmd: sudo snap install nvim --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            - "choco:lua;scoop:main/lua"
            - "choco:luarocks;scoop:main/luarocks"
            - "choco:neovim;scoop:main/neovim;winget:Neovim.Neovim"
        platforms: [windows]
      - task: neovim-config

  neovim-config:
    desc: Install Neovim config
    cmds:
      - cmd: |
          echo "TODO: Integrate the neovim config in the same repo as the Taskfile"

  vscode:
    desc: Install VS Code
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["visual-studio-code"]
        platforms: [darwin]
      - cmd: sudo snap install code --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:vscode;scoop:extras/vscode;winget:Microsoft.VisualStudioCode"]
        platforms: [windows]

  vscodium:
    desc: Install VSCodium (open source build of VS Code)
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["vscodium"]
        platforms: [darwin]
      - cmd: sudo snap install codium --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:vscodium;scoop:extras/vscodium;winget:VSCodium.VSCodium"]
        platforms: [windows]

  zed:
    desc: Install Zed
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["zed"]
        platforms: [darwin]
      - cmd: curl -f https://zed.dev/install.sh | sh
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["scoop:extras/zed"]
        platforms: [windows]

  pycharm:
    desc: Install PyCharm
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["pycharm"]
        platforms: [darwin]
      - cmd: sudo snap install pycharm-professional --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES:
            ["choco:pycharm-professional;scoop:extras/pycharm-professional;winget:JetBrains.PyCharm.Professional"]
        platforms: [windows]

  sublime:
    desc: Install Sublime Text
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["sublime-text"]
        platforms: [darwin]
      - cmd: sudo snap install sublime-text --classic
        platforms: [linux]
      - task: c:windows
        vars:
          PACKAGES: ["choco:sublimetext4;scoop:extras/sublime-text;winget:SublimeHQ.SublimeText.4"]
        platforms: [windows]
