---
- name: Install Terraform
  hosts: all
  become: yes
  vars:
    terraform_version: "0.0.0"
    terraform_download_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    terraform_install_dir: "/usr/local/bin"
  tasks:
    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present

    - name: Create temporary directory for Terraform installation
      ansible.builtin.tempfile:
        state: directory
      register: temp_dir

    - name: Download Terraform
      get_url:
        url: "{{ terraform_download_url }}"
        dest: "{{ temp_dir.path }}/terraform.zip"

    - name: Unzip Terraform binary
      unarchive:
        src: "{{ temp_dir.path }}/terraform.zip"
        dest: "{{ terraform_install_dir }}"
        remote_src: yes
        mode: 0755

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent

    - name: Verify Terraform installation
      command: "terraform version"
      register: terraform_version_output
      changed_when: false

    - name: Display Terraform version
      debug:
        msg: "Terraform has been installed: {{ terraform_version_output.stdout }}"
