# add @ the end of local .bash_profile
# cat bash_profile >> $HOME/.bash_profile

which thefuck > /dev/null && eval $(thefuck --alias)


# Git branch in prompt.

parse_git_branch() {
  which git > /dev/null && git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
  which git > /dev/null || echo 'no git installed'
}

export PS1="\u@\h \W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "