
version: '3'

vars:
  SHELL:
    sh: bash
    windows: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command

tasks:
  default:
    desc: List available Linux install tasks
    silent: true
    cmds:
      - task --list

  alpine:
    desc: Install Alpine Linux (WSL)
    cmds:
      - |
        wsl --install -d Alpine || wsl --import Alpine "$env:USERPROFILE\\Alpine" "https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-minirootfs-latest-x86_64.tar.gz"

  alpine:attach:
    desc: Attach to Alpine Linux (WSL)
    cmds:
      - wsl -d Alpine

  ubuntu:
    desc: Install Ubuntu (WSL)
    cmds:
      - wsl --install -d Ubuntu

  ubuntu:attach:
    desc: Attach to Ubuntu (WSL)
    cmds:
      - wsl -d Ubuntu

  fedora:
    desc: Install Fedora (WSL)
    cmds:
      - wsl --install -d Fedora || wsl --import Fedora "$env:USERPROFILE\\Fedora" "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-40-1.14.x86_64.raw.xz"

  fedora:attach:
    desc: Attach to Fedora (WSL)
    cmds:
      - wsl -d Fedora

  arch:
    desc: Install Arch Linux (WSL, unofficial)
    cmds:
      - |
        wsl --import Arch "$env:USERPROFILE\\Arch" "https://github.com/yuk7/ArchWSL/releases/latest/download/Arch.tar.gz"

  arch:attach:
    desc: Attach to Arch Linux (WSL)
    cmds:
      - wsl -d Arch

  nixos:
    desc: Install NixOS (WSL, unofficial)
    cmds:
      - |
        wsl --import NixOS "$env:USERPROFILE\\NixOS" "https://github.com/nix-community/NixOS-WSL/releases/latest/download/nixos-wsl.tar.gz"

  nixos:attach:
    desc: Attach to NixOS (WSL)
    cmds:
      - wsl -d NixOS
