version: "3"

tasks:
  default:
    desc: List available Linux install tasks
    silent: true
    cmds:
      - task --list
  generic:
    desc: Generic task for installing Linux distributions (WSL)
    cmds:
      - cmd: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./install.ps1 -Package "{{.LINUX_LABEL}}" {{if .LINUX_URL}}-Url "{{.LINUX_URL}}"{{end}}
        platforms: [windows]
    internal: true

  alpine:
    desc: Install Alpine Linux (WSL)
    cmds:
      - task: generic
        vars:
          LINUX_LABEL: Alpine
          LINUX_URL: "https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-minirootfs-latest-x86_64.tar.gz"
        platforms: [windows]

  alpine:attach:
    desc: Attach to Alpine Linux (WSL)
    cmds:
      - cmd: wsl -d Alpine
        platforms: [windows]

  ubuntu:
    desc: Install Ubuntu (WSL)
    cmds:
      - task: generic
        vars:
          LINUX_LABEL: "Ubuntu-24.04"
        platforms: [windows]

  ubuntu:attach:
    desc: Attach to Ubuntu (WSL)
    cmds:
      - cmd: wsl -d Ubuntu-24.04
        platforms: [windows]

  # fedora:
  #   desc: Install Fedora (WSL)
  #   cmds:
  #     - wsl --install -d Fedora || wsl --import Fedora "$env:USERPROFILE\\Fedora" "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-40-1.14.x86_64.raw.xz"

  # fedora:attach:
  #   desc: Attach to Fedora (WSL)
  #   cmds:
  #     - wsl -d Fedora

  # arch:
  #   desc: Install Arch Linux (WSL, unofficial)
  #   cmds:
  #     - |
  #       wsl --import Arch "$env:USERPROFILE\\Arch" "https://github.com/yuk7/ArchWSL/releases/latest/download/Arch.tar.gz"

  # arch:attach:
  #   desc: Attach to Arch Linux (WSL)
  #   cmds:
  #     - wsl -d Arch

  # nixos:
  #   desc: Install NixOS (WSL, unofficial)
  #   cmds:
  #     - |
  #       wsl --import NixOS "$env:USERPROFILE\\NixOS" "https://github.com/nix-community/NixOS-WSL/releases/latest/download/nixos-wsl.tar.gz"

  # nixos:attach:
  #   desc: Attach to NixOS (WSL)
  #   cmds:
  #     - wsl -d NixOS
