#!/usr/bin/env bash

[ -n "$GLVM_DEBUG" ] && {
    set -x
}

function glvm() {

  command=$1

  if [[ -f "$GLVM_ROOT/lib/handlers/$command.sh" ]]; then
    source "$GLVM_ROOT/lib/handlers/$command.sh"
    command="handler_$command"

    $command ${@:2}

  else

    echo -n "Usage: glvm [command|manager]

Description:
  GVM is the Go Version Manager

Commands:
  version    - print the gvm version number
  help       - display this usage text

Handlers:
"

    find $GLVM_ROOT/lib/handlers -type f | while read file; do
      handler=$(basename $file)
      handler=${handler/.sh/}
      echo "  ${handler} - ${handler} manager"
    done

  fi

}
