version: "3"

tasks:
  default:
    desc: default action - lists the tasks (you're looking at it)
    silent: true
    cmds:
      - task --list

  aliases:update:
    desc: Update Local Aliases
    cmd: |
