version: "3"

# vars:
#   SHELL:
#     sh: bash
#     windows: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command

tasks:
  default:
    silent: true
    cmds:
      - task --list

  darwin:
    cmds:
      - for:
          var: PACKAGES
        cmd: |
          read repo package_name <<< ${package/\// }
          args=""
          [ -z "$package_name" ] && package_name=$repo
          [ -z "$package_name" ] && args="--$repo"
          if {{if .CLI_FORCE}}[ 1 -eq 1 ]{{else}}! brew list $args $package &>/dev/null{{end}}; then
            brew install $args{{if .FORCE}} --force{{end}} $package_name
          else
            echo {{.ITEM}} already installed
          fi
        platforms: [darwin]
      - cmd: echo "'brew' is only available on MacOS"
        platforms: [linux, windows]
    desc: Install a Package under Darwin, using Homebrew
    internal: true

  windows:
    cmds:
      - for:
          var: PACKAGES
        cmd: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./install.ps1 -Package {{.ITEM}} {{if .CLI_FORCE}}-Force{{end}}
        platforms: [windows]
      - cmd: echo "Windows installers are not available on Darwin or Linux"
        platforms: [darwin, linux]
    desc: Install a Package under Windows
    internal: true
