version: "3"

includes:
  c:
    taskfile: ../common
    dir: ../common
  l:
    taskfile: ../language
    dir: ../language

tasks:
  default:
    desc: default action - lists the tasks (you're looking at it)
    silent: true
    cmds:
      - task: alacritty
      - task: ghostty
      - task: iterm
      - task: warp

  # https://alacritty.org/
  #
  alacritty:
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: ["alacritty"]
        platforms: [darwin]
      # TODO: https://alacritty.org/ => check installation steps
      - task: c:windows
        vars:
          PACKAGE:
            ["winget:Alacritty.Alacritty;choco:alacritty;scoop:extras/alacritty"]
        platforms: [windows]
      - task: alacritty:config
    desc: Install Alacritty Termianl (Windows)

  alacritty:config:
    cmds:
      - cmd: |
          echo "Must write config script for alacritty"
    desc: Configure Alacritty

  # https://ghostty.org/
  #
  ghostty:
    desc: Install Ghostty Terminal (Darwin,Linux)
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: [cask/ghostty]
        platforms: [darwin]
      # TODO: https://ghostty.org/docs/install/binary#linux-(official) => check installation steps
      - task: ghostty:config

  ghostty:config:
    cmds:
      - cmd: |
          config="$HOME/Library/Application Support/com.mitchellh.ghostty/config"
          mv "$config" "$config.bak.$(date +%s)"
          ln -s $(pwd)/ghostty.config "$config"
        platforms: [darwin]
      - cmd: |
          config="$HOME/Library/Application Support/com.mitchellh.ghostty/config"
          mv "$config" "$config.bak.$(date +%s)"
          ln -s $(pwd)/ghostty.config "$config"
        platforms: [linux]
    desc: Configure Ghostty

  # https://iterm2.com/
  #
  iterm:
    desc: Install iTerm Terminal (Darwin)
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: [cask/iterm2, cask/itermai]
        platforms: [darwin]
      - task: iterm:config

  iterm:config:
    cmds:
      - cmd: |
          echo "Must write config script for iterm"
        platforms: [darwin, linux]
    desc: Configure Ghostty

  # https://github.com/microsoft/terminal
  #
  terminal:
    desc: Install Terminal (Darwin,Linux,Windows)
    cmds:
      - cmd: |
          echo "Microsoft Terminal is not supported on Darwin and Linux"
        platforms: [darwin, linux]
      - task: c:windows
        vars:
          PACKAGES: [winget:Microsoft.WindowsTerminal;choco:microsoft-windows-terminal;scoop:extras/windows-terminal]
        platforms: [windows]

  # https://www.warp.dev/
  #
  warp:
    desc: Install Warp Terminal (Darwin,Linux,Windows)
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: [cask/warp]
        platforms: [darwin]
      # TODO: https://www.warp.dev/linux-terminal => check installation steps
      - task: c:windows
        vars:
          PACKAGES: [winget:Warp.Warp;choco:warp;scoop:warp]
        platforms: [windows]
      - task: warp:config

  warp:config:
    cmds:
      - cmd: |
          echo "Must write config script for warp"
        platforms: [darwin, linux]
    desc: Configure Ghostty

  # https://wezterm.org/index.html
  #
  wezterm:
    desc: Install Wezterm Terminal (Windows)
    cmds:
      - task: c:darwin
        vars:
          PACKAGES: [wezterm]
        platforms: [darwin]
      - task: c:windows
        vars:
          PACKAGES: [winget:wez.wezterm;choco:wezterm;scoop:extras/wezterm]
        platforms: [windows]
      - task: wezterm:config

  wezterm:config:
    cmds:
      - cmd: |
          echo "Must write config script for wezterm"
        platforms: [darwin, linux]
    desc: Configure Ghostty
